spring:
  datasource:
    url: jdbc:h2:mem:simplymed;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false

  # Consola H2 - Nota: la consola H2 debe ir aquí, no al final
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8081

# CORS simple para front local
app:
  cors:
    origins:
      - http://localhost:5173
      - http://localhost:3000
